[package]
name = "git-suggest-ownership"
version = "0.1.1"
edition = "2021"

[profile.release]
lto = "thin"

[dependencies]
anyhow = "1.0"
structopt = "0.3"
log = "0.4"
stderrlog = "0.5"
indicatif = "0.17"
rayon = "1.5"
thread_local = "1.1"
git2 = { version = "0.15", default-features = false }
