name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}    
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy, rustfmt
    - name: Build
      run: cargo build --verbose
    - name: clippy
      run: cargo clippy -- -D warnings
    - name: fmt
      run: cargo fmt --all -- --check
    - name: Run tests
      run: cargo test --verbose
    - name: Run application
      run: |
        cargo run -r -- --help
        cargo run -r -- --email example@example.com
        cargo run -r -- --show-authors
        cargo run -r -- --flat --email example@example.com
        cargo run -r -- --max-age 3M --email example@example.com
